### ISSUE TITLE
Add first draft of materials for Columnar analysis and Awkward session

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/us-atlas-idap-training-2024#2]
## Description

Have @jpivarski add a first draft of the materials to be taught at the 2024 [US ATLAS / IRIS-HEP Analysis Software Training Event](https://indico.cern.ch/event/1376945/) by Monday, 15 July 2024 in a pull request to this repo.

## Training event session

* Indico: [Columnar analysis and Awkward](https://indico.cern.ch/event/1376945/contributions/5787146/)
* Date: 18 July, 2024
* Lead instructor: @jpivarski 

## Reference material

* [Columnar analysis and Awkward](https://indico.cern.ch/event/1383972/contributions/5825303/) from the June 2024 US CMS / IRIS-HEP training event.

## Scope

The target audience at the training event will be similar to the US CMS / IRIS-HEP training event of being ATLAS Ph.D. students.

The goal is to use the [UChicago Coffea-casa deployment](https://coffea.af.uchicago.edu/) as the students will be US ATLAS members and this would be the best choice to support their credentials while also having access to Coffea-casa. If there are software or data requirements that will be needed in advance please coordinate with the UChicago SSL team and Oksana Shadura (`@oshadura`). This will be less relevant for this contribution as the session can all be run in browser with Jupyter Lite.

**Comment by jpivarski** [comment]
This is a stable URL to the GitHub repo that I will eventually use to present: https://github.com/jpivarski-talks/2024-07-18-usatlas-seattle-tutorial

Of course, a lot of names will need to get fixed (~~CMS~~ → ATLAS) and I'll need to ensure that it will work on the day of presentation, but you can count on this URL being _the_ URL.
