### ISSUE TITLE
Add first draft of materials for PHYSLITE session

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/us-atlas-idap-training-2024#3]
## Description

Have @ekourlit add a first draft of the materials to be taught at the 2024 [US ATLAS / IRIS-HEP Analysis Software Training Event](https://indico.cern.ch/event/1376945/) by Monday, 15 July 2024 in a pull request to this repo.

## Training event session

* Indico: [PHYSLITE](https://indico.cern.ch/event/1376945/contributions/6028275/)
* Date: 18 July, 2024
* Lead instructor: @ekourlit 

## Reference material

* [How to use a PHYSLITE file](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/c1bdf1c3fe5999bab113386218165f43350acd65/for-research/physlite_tutorial.ipynb) from the https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata repository.

## Scope

The target audience at the training event will be US ATLAS Ph.D. students.

The goal is to use the [UChicago Coffea-casa deployment](https://coffea.af.uchicago.edu/) as the students will be US ATLAS members and this would be the best choice to support their credentials while also having access to Coffea-casa. If there are software or data requirements that will be needed in advance please coordinate with the UChicago SSL team and Oksana Shadura (`@oshadura`).

**Comment by ekourlit** [comment]
**References:**

1. Internal short tutorial given by Nikolai Hartmann in December 2023: https://gitlab.cern.ch/nihartma/end-of-year-physlite-tutorial
2. Notebook we released along with the Open Data: https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/master/for-research/physlite_tutorial.ipynb
3. ⭐️ coffea NanoEvents notebook: https://github.com/iris-hep/uscms-idap-training/blob/main/coffea/coffea-01-nanoevents.ipynb

**Comment by ekourlit** [comment]
That is a 30mins slot so I plan to split it in 10mins talk intro to PHYSLITE and then a 20mins tutorial of how to load a PHYSLITE file with `coffea` and the `PHYSLITESchema`. However, proper introduction to `coffea` will come later: [Coffea columnar analysis framework](https://indico.cern.ch/event/1376945/timetable/?view=standard#15-coffea-columnar-analysis-fr). ATLAS Open Data in PHYSLITE format will be used.

**Comment by matthewfeickert** [comment]
@ekourlit can you make a PR with your `PHYSLITE` branch? I realize that you may want to revise more, but it would be good to get first drafts of the material in so that people can start to cross reference each other.

**Comment by matthewfeickert** [comment]
Resolved by PR #14 (first draft).
