### ISSUE TITLE
Add first draft of materials for Coffea columnar analysis framework session

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/us-atlas-idap-training-2024#6]
## Description

Have @matthewfeickert add a first draft of the materials to be taught at the 2024 [US ATLAS / IRIS-HEP Analysis Software Training Event](https://indico.cern.ch/event/1376945/) by Monday, 15 July 2024 in a pull request to this repo.

## Training event session

* Indico: [Coffea columnar analysis framework](https://indico.cern.ch/event/1376945/contributions/5787150/)
* Date: 18 July, 2024
* Lead instructor: @matthewfeickert 

## Reference material

* [Coffea columnar analysis framework](https://indico.cern.ch/event/1383972/contributions/5825307/) from the June 2024 US CMS / IRIS-HEP training event.

## Scope

The target audience at the training event will be US ATLAS Ph.D. students.

The goal is to use the [UChicago Coffea-casa deployment](https://coffea.af.uchicago.edu/) as the students will be US ATLAS members and this would be the best choice to support their credentials while also having access to Coffea-casa. If there are software or data requirements that will be needed in advance please coordinate with the UChicago SSL team and Oksana Shadura (`@oshadura`).

**Comment by matthewfeickert** [comment]
To quickly capture feedback from @oshadura and @alexander-held from the 2024-07-08 instructor team meeting (please comment with corrections if I captured feedback wrong):

Based on https://github.com/iris-hep/uscms-idap-training/tree/437edaf5ef9cf961e047cadc16721d77d144e907/coffea

* Update [`coffea-01-nanoevents.ipynb`](https://github.com/iris-hep/uscms-idap-training/blob/437edaf5ef9cf961e047cadc16721d77d144e907/coffea/coffea-01-nanoevents.ipynb) to use PHYSLITE
* Skip [coffea-02-applying_corrections.ipynb](https://github.com/iris-hep/uscms-idap-training/blob/437edaf5ef9cf961e047cadc16721d77d144e907/coffea/coffea-02-applying_corrections.ipynb) as we don't use correctionlib in ATLAS
* Keep [coffea-03-analysis-tools.ipynb](https://github.com/iris-hep/uscms-idap-training/blob/437edaf5ef9cf961e047cadc16721d77d144e907/coffea/coffea-03-analysis-tools.ipynb)
* Revise and merge [coffea-04-processing.ipynb](https://github.com/iris-hep/uscms-idap-training/blob/437edaf5ef9cf961e047cadc16721d77d144e907/coffea/coffea-04-processing.ipynb) and [coffea-05-scaleout.ipynb](https://github.com/iris-hep/uscms-idap-training/blob/437edaf5ef9cf961e047cadc16721d77d144e907/coffea/coffea-05-scaleout.ipynb)
* Update [fileset.json](https://github.com/iris-hep/uscms-idap-training/blob/437edaf5ef9cf961e047cadc16721d77d144e907/coffea/fileset.json) to use ATLAS open data.

**Comment by alexander-held** [comment]
I think the first notebook could go into @ekourlit's PHYSLITE session as well.

**Comment by matthewfeickert** [comment]
Resolved by PR #15, #22, #24, #26, #29, #32.
