### ISSUE TITLE
Add first draft of materials for Sample game introduction

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/us-atlas-idap-training-2024#7]
## Description

Have @alexander-held add a first draft of the materials to be taught at the 2024 [US ATLAS / IRIS-HEP Analysis Software Training Event](https://indico.cern.ch/event/1376945/) by Monday, 15 July 2024 in a pull request to this repo.

## Training event session

* Indico: [Sample game introduction](https://indico.cern.ch/event/1376945/contributions/6028277/)
* Date: 18 July, 2024
* Lead instructor: @alexander-held 

## Reference material

* [Sample game introduction](https://indico.cern.ch/event/1383972/contributions/6017104/) from the June 2024 US CMS / IRIS-HEP training event.

## Scope

The target audience at the training event will be US ATLAS Ph.D. students.

The goal is to use the [UChicago Coffea-casa deployment](https://coffea.af.uchicago.edu/) as the students will be US ATLAS members and this would be the best choice to support their credentials while also having access to Coffea-casa. If there are software or data requirements that will be needed in advance please coordinate with the UChicago SSL team and Oksana Shadura (`@oshadura`).

**Comment by matthewfeickert** [comment]
@alexander-held as I'm nearly 2 weeks late in getting this up let me know if there's anything that I can do to assist you in getting the simulation files needed for this.

**Comment by alexander-held** [comment]
resolved by #28
